/* Generated By:JavaCC: Do not edit this line. STOBParserConstants.java */
package org.stobml.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface STOBParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ABSTRACT = 7;
  /** RegularExpression Id. */
  int ASSERT = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int BREAK = 10;
  /** RegularExpression Id. */
  int BYTE = 11;
  /** RegularExpression Id. */
  int CASE = 12;
  /** RegularExpression Id. */
  int CATCH = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int CONST = 16;
  /** RegularExpression Id. */
  int CONTINUE = 17;
  /** RegularExpression Id. */
  int _DEFAULT = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int DOUBLE = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int ENUM = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int FINAL = 25;
  /** RegularExpression Id. */
  int FINALLY = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int GOTO = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int IMPLEMENTS = 31;
  /** RegularExpression Id. */
  int IMPORT = 32;
  /** RegularExpression Id. */
  int INSTANCEOF = 33;
  /** RegularExpression Id. */
  int INT = 34;
  /** RegularExpression Id. */
  int INTERFACE = 35;
  /** RegularExpression Id. */
  int LONG = 36;
  /** RegularExpression Id. */
  int NATIVE = 37;
  /** RegularExpression Id. */
  int NEW = 38;
  /** RegularExpression Id. */
  int NULL = 39;
  /** RegularExpression Id. */
  int PACKAGE = 40;
  /** RegularExpression Id. */
  int PRIVATE = 41;
  /** RegularExpression Id. */
  int PROTECTED = 42;
  /** RegularExpression Id. */
  int PUBLIC = 43;
  /** RegularExpression Id. */
  int RETURN = 44;
  /** RegularExpression Id. */
  int SHORT = 45;
  /** RegularExpression Id. */
  int STATIC = 46;
  /** RegularExpression Id. */
  int STRICTFP = 47;
  /** RegularExpression Id. */
  int SUPER = 48;
  /** RegularExpression Id. */
  int SWITCH = 49;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 50;
  /** RegularExpression Id. */
  int THIS = 51;
  /** RegularExpression Id. */
  int THROW = 52;
  /** RegularExpression Id. */
  int THROWS = 53;
  /** RegularExpression Id. */
  int TRANSIENT = 54;
  /** RegularExpression Id. */
  int TRUE = 55;
  /** RegularExpression Id. */
  int TRY = 56;
  /** RegularExpression Id. */
  int VOID = 57;
  /** RegularExpression Id. */
  int VOLATILE = 58;
  /** RegularExpression Id. */
  int WHILE = 59;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 60;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 61;
  /** RegularExpression Id. */
  int HEX_LITERAL = 62;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 63;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 64;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 65;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 66;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 67;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 68;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 69;
  /** RegularExpression Id. */
  int STRING_LITERAL = 70;
  /** RegularExpression Id. */
  int IDENTIFIER = 71;
  /** RegularExpression Id. */
  int LETTER = 72;
  /** RegularExpression Id. */
  int PART_LETTER = 73;
  /** RegularExpression Id. */
  int LPAREN = 74;
  /** RegularExpression Id. */
  int RPAREN = 75;
  /** RegularExpression Id. */
  int LBRACE = 76;
  /** RegularExpression Id. */
  int RBRACE = 77;
  /** RegularExpression Id. */
  int LBRACKET = 78;
  /** RegularExpression Id. */
  int RBRACKET = 79;
  /** RegularExpression Id. */
  int SEMICOLON = 80;
  /** RegularExpression Id. */
  int COMMA = 81;
  /** RegularExpression Id. */
  int DOT = 82;
  /** RegularExpression Id. */
  int AT = 83;
  /** RegularExpression Id. */
  int ASSIGN = 84;
  /** RegularExpression Id. */
  int LT = 85;
  /** RegularExpression Id. */
  int BANG = 86;
  /** RegularExpression Id. */
  int TILDE = 87;
  /** RegularExpression Id. */
  int HOOK = 88;
  /** RegularExpression Id. */
  int COLON = 89;
  /** RegularExpression Id. */
  int EQ = 90;
  /** RegularExpression Id. */
  int LE = 91;
  /** RegularExpression Id. */
  int GE = 92;
  /** RegularExpression Id. */
  int NE = 93;
  /** RegularExpression Id. */
  int SC_OR = 94;
  /** RegularExpression Id. */
  int SC_AND = 95;
  /** RegularExpression Id. */
  int INCR = 96;
  /** RegularExpression Id. */
  int DECR = 97;
  /** RegularExpression Id. */
  int PLUS = 98;
  /** RegularExpression Id. */
  int MINUS = 99;
  /** RegularExpression Id. */
  int STAR = 100;
  /** RegularExpression Id. */
  int SLASH = 101;
  /** RegularExpression Id. */
  int BIT_AND = 102;
  /** RegularExpression Id. */
  int BIT_OR = 103;
  /** RegularExpression Id. */
  int XOR = 104;
  /** RegularExpression Id. */
  int REM = 105;
  /** RegularExpression Id. */
  int LSHIFT = 106;
  /** RegularExpression Id. */
  int PLUSASSIGN = 107;
  /** RegularExpression Id. */
  int MINUSASSIGN = 108;
  /** RegularExpression Id. */
  int STARASSIGN = 109;
  /** RegularExpression Id. */
  int SLASHASSIGN = 110;
  /** RegularExpression Id. */
  int ANDASSIGN = 111;
  /** RegularExpression Id. */
  int ORASSIGN = 112;
  /** RegularExpression Id. */
  int XORASSIGN = 113;
  /** RegularExpression Id. */
  int REMASSIGN = 114;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 115;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 116;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 117;
  /** RegularExpression Id. */
  int ELLIPSIS = 118;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 119;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 120;
  /** RegularExpression Id. */
  int GT = 121;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
