// this file is initially generated by bisonc++, but then it is
// maintained by human

// Generated by Bisonc++ V6.04.01 on Sun, 03 Apr 2022 14:17:52 +0300

	// Include this file in the sources of the class parser.

// $insert class.h
#include "parser.hpp"


inline void parser::error()
{
	std::cerr << "Syntax error\n";
}

// $insert lex
inline int parser::lex()
{
	char c;

	std::cin.get(c);

	// check for EOF
	if(!std::cin){
		return 0;
	}

	return c;
}

inline void parser::print()         
{
}

inline void parser::exceptionHandler(std::exception const &exc)         
{
	throw;              // re-implement to handle exceptions thrown by actions
}


	// Add here includes that are only required for the compilation 
	// of parser's sources.



	// UN-comment the next using-declaration if you want to use
	// int parser's sources symbols from the namespace std without
	// specifying std::

//using namespace std;
